[project]
name = "first-steps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.2",
    "loguru>=0.7.3",
    "motor>=3.7.1",
    "uvicorn>=0.35.0",
]
